{
 "title": "BookStore dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Orders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Wattage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_wattage", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "Messages Received",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "messages_received", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg. Wattage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_wattage / messages_received",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}