version: '3.7'
#
# Docker Reference Docs
# https://docs.docker.com/compose/compose-file/build/

services:
  currentcost:
    image: ${DOCKER_REGISTRY-}currentcost
    container_name: 'current-cost'
    build:
      context: .
      dockerfile: CurrentCost/Dockerfile
    env_file:
      - prod.env
    ports:
      - 80:80 # expose to host LAN
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - currentcost

  #prometheus: # https://prometheus.io/docs/introduction/overview/
  #  # https://prometheus.io/docs/guides/cadvisor/#docker-compose-configuration
  #  image: prom/prometheus:latest
  #  container_name: current-cost_prometheus
  #  env_file:
  #    - prod.env
  #  ports:
  #    - 9090:9090 # Expose to LAN
  #  command:
  #  - --config.file=/etc/prometheus/prometheus.yml
  #  volumes:
  #    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #  networks:
  #    - currentcost
  #  depends_on:
  #    - cadvisor

  #cadvisor:
  #  image: gcr.io/cadvisor/cadvisor:latest
  #  container_name: current-cost_cadvisor
  #  ports:
  #  - 127.0.0.1:9080:8080 # restrict to host only NOT LAN
  #  volumes:
  #  - /:/rootfs:ro
  #  - /var/run:/var/run:rw
  #  - /sys:/sys:ro
  #  - /var/lib/docker/:/var/lib/docker:ro
  #  networks:
  #    - currentcost

  rabbitmq: # Defaults to guest / guest
    image: rabbitmq:3.11.5-management-alpine
    container_name: 'current-cost_rabbitmq'
    env_file:
      - prod.env
    ports:
      - 127.0.0.1:5672:5672 #   restrict to host only NOT LAN
      - 127.0.0.1:15672:15672 # restrict to host only NOT LAN
    volumes:
      - ~/.docker-conf/current-cost/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/current-cost/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - currentcost

  postgres:
    image: postgres:15.1-alpine
    container_name: 'current-cost_postgres'
    restart: always
    env_file:
      - prod.env
    ports:
      - 127.0.0.1:5432:5432 #   restrict to host only NOT LAN
    networks:
      - currentcost

networks:
  currentcost:
